name: LeetCode Stats

on:
  schedule:
    - cron: "0 * * * *" # runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anuraghazra/leetcode-stats-readme@master
        with:
          LEETCODE_USERNAME: manavtries
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Updated LeetCode stats"
